### ISSUE TITLE
Feature: Adding semver ranges to the packages in the list

### ISSUE THREAD

**Issue by mischah** [micromata/check-packages#2]
This would make it possible to define certain versions or version ranges as allowed/disallowed.

Specifying the version range should be optional.

Example list:

```
[
  "react",
  "react-dom@^2.2.1",
  "redux@>=1.0.0-rc.0 <1.0.1",
  "react-redux@^2 <2.2 || > 2.3"
]
```

I’m not sure about the combination between package name and semver range via the `@`? Any better ideas?

I think something like this is easier than having to use an array of object, right?

```
[
  {
    package: "react",
    versions: ""
  },
  {
    package: "react-dom",
    versions: ">2.1"
  }
]
```

**Comment by mischah** [comment]
P.S. I would love to work on this 😘

**Comment by chrkhl** [comment]
I already had this feature in mind and would prefer the first option (array of strings).

**Comment by chrkhl** [comment]
I opened pull request #4 for this feature.

@mischah: Would be nice if you could throw an eye :eye: on this :wink:
